apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdf-visual-transform
  namespace: argocd
  labels:
    app: rdf-visual-transform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdf-visual-transform
  template:
    metadata:
      labels:
        app: rdf-visual-transform
    spec:
      containers:
        - name: rdf-visual-transform
          image: ghcr.io/mrkmrk00/rdf-visual-transform:4887a19626a2ba8aaea07e41af0936b5067d495a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
